### create ORGANIZATION
POST http://localhost:3333/organization
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMmYzYzc2Zi05M2U3LTQ1ZTgtOTZlNy0zMDI3MTdmZmQwMDciLCJpYXQiOjE3NDIxNjE1ODIsImV4cCI6MTc0Mjc2NjM4Mn0.HrgvN_5bD9CpCjfjYT3czhclNJgyqVo1uA6mazeSbj4"
{
  "name": "OAK Labs",
  "domain": "oak.team",
  "shouldAttachUsersByDomain": true
}

### get MEMBERSHIP
GET http://localhost:3333/organizations/teste-1/membership
Content-Type: application/json
Authorization: Bearer {{bearer}}