### GET
GET http://localhost:3333/users
Content-Type: application/json


### POST
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Samuel",
  "email": "samuel@acme.com",
  "password": "123456"
}

### POST
POST http://localhost:3333/sessions/password
Content-Type: application/json

{
  "email": "samuel@acme.com",
  "password": "123456"
}

### GET
GET http://localhost:3333/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYzgxNTQ2Ni1jN2YxLTQ5ZmYtOGJhMi04Y2Y4MDFlYmNiZGYiLCJpYXQiOjE3MzkyMzUzODEsImV4cCI6MTczOTg0MDE4MX0.I3F5WcNl8knrFEiBwpaTq55PcPQgYSxJgDQk7MCnMmw