### GET
GET http://localhost:3333/users
Content-Type: application/json


### POST
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "Samuel",
  "email": "samuel@acme.com",
  "password": "123456"
}

### POST
POST http://localhost:3333/sessions/password
Content-Type: application/json

{
  "email": "samuel@acme.com",
  "password": "123456"
}